version: '2'

services:

  maria-tests:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: MyTestDatabase
    networks:
       - back

  maria-local:
    image: mariadb:latest
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: MyTestDatabase
    networks:
      - back

  composer56:
    build: env/builds/composer-php5.6
    volumes:
      - ./:/app
    command: php -v
    
  testunit56:
    build: env/builds/php5.6
    volumes:
      - ./:/app
    command: php vendor/bin/phpunit -c phpunit.xml
    environment:
      SQL_HOST: maria-tests
      SQL_DATABASE: MyTestDatabase
      SQL_PORT: 3306
      SQL_USER: root
      SQL_PASSWORD: secret
    networks:
      - back
    links:
      - maria-tests

networks:
  back:
    driver: bridge